# Generated by Django 4.2.14 on 2024-07-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, unique=True)),
                ('sn', models.CharField(max_length=50, unique=True)),
                ('vc', models.CharField(max_length=50, unique=True)),
                ('ac', models.CharField(max_length=50, unique=True)),
                ('vkey', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('finger_id', models.AutoField(primary_key=True, serialize=False)),
                ('finger_data', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
