# Generated by Django 4.2.14 on 2024-07-17 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
